### ISSUE TITLE
LoadError in Julia v0.4.6

### ISSUE THREAD

**Issue by ghost** [OFAI/BayesianNonparametrics.jl#1]
Hi... Interesting package!  Went to play around with this, and got this error during the import:

julia> using BNP

INFO: Precompiling module Distributions...
INFO: Precompiling module Clustering...
ERROR: LoadError: LoadError: UndefVarError: @view not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
while loading /home/mwojnowicz/.julia/v0.4/BNP/src/distfunctions.jl, in expression starting on line 22
while loading /home/mwojnowicz/.julia/v0.4/BNP/src/BNP.jl, in expression starting on line 12

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce* (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-amazon-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by trappmartin** [comment]
Hi,
thanks for your interest.

Apparently, you need julia version 0.5 to run the packages as it heavily uses views.
Moreover, please use the package
_BayesianNonparametrics.jl_
instead of the BNP.jl package.

You should then be able to run the following in your julia environment.

```
using BayesianNonparametrics
(X, Y) = bloobs();
size(X)
```
which should give you an array of size (102,2).

Best,
Martin
